### ISSUE TITLE
"Install demos" with Avada theme 

### ISSUE THREAD

**Issue by stuartasutton** [ld4pe/ld4pe-general#23]
@davidwtalley While I am sure they take up space, I'd like the demos installed for use with the DCMI site. They do recommend installing when the implementation is new with the following admonition:

> "The easiest way to import our demo content is to use our Demo Content Importer. Our importer will give you all pages and posts, several sample sliders, widgets, Fusion Theme Options, assigned pages, and more. This is recommended to do on fresh installs. It will not replace content like posts, pages, portfolio, etc , it will not delete current menus but configure our demo menus, and it will not replace but add sliders. It will, however, replace Fusion Theme Options, Reading settings and Widget settings. To import our demo content, please see the steps below."

Please advise. These examples would be VERY useful since they provide examples of implementing certain kinds of pages/posts -- e.g., FAQ etc.

**Comment by stuartasutton** [comment]
I'd assume that the admonition would not be applicable with bringing up Avada as theme for DCMI since it would be 'original' without any site specific settings etc.

**Comment by davidwtalley** [comment]
Would it meet needs to set up a separate test site with these demos in place? I am quite leery of risking the changes described on the existing LD4PE site. 
- David 
On Oct 4, 2015 7:05 AM, Stuart Sutton <notifications@github.com> wrote:@davidwtalley While I am sure they take up space, but I'd like the demons installed for use with the DCMI site. They do recommend installing when the implementation is new with the following admonition:


"The easiest way to import our demo content is to use our Demo Content Importer. Our importer will give you all pages and posts, several sample sliders, widgets, Fusion Theme Options, assigned pages, and more. This is recommended to do on fresh installs. It will not replace content like posts, pages, portfolio, etc , it will not delete current menus but configure our demo menus, and it will not replace but add sliders. It will, however, replace Fusion Theme Options, Reading settings and Widget settings. To import our demo content, please see the steps below."


Please advise. These examples would be VERY useful since they provide examples of implementing certain kinds of pages/posts -- e.g., FAQ etc.

**Comment by stuartasutton** [comment]
Understood. Over the past several days, I brought up Avada on the local WP on my Mac. I then downloaded one of demos. It certainly would have wreaked havoc on any existing setting (had I had any :-).
