### ISSUE TITLE
Link "icon" causing problems

### ISSUE THREAD

**Issue by stuartasutton** [ld4pe/ld4pe-general#32]
The icon solution to the UX issue with links works in most cases and causes problems in others. Currently, when there is an image inserted in text and WP does its trick of making the image a link to itself, the new link icon is inserted 
![screenshot 2015-11-22 05 44 38](https://cloud.githubusercontent.com/assets/2939046/11324107/55bcd758-90dc-11e5-925a-884c50527956.png)

But, when the creator wants text to wrap the image (i.e., text aligned with the top of the image on either left or right), that no longer works:
![screenshot 2015-11-22 05 48 04](https://cloud.githubusercontent.com/assets/2939046/11324114/a9d214ac-90dc-11e5-823c-e1b9fa6e58d3.png)

**Comment by davidwtalley** [comment]
I have two responses to this. One is to keep WP from doing that automatic link-an-image-to-itself that it wants to do by default. That's usually a useless link because it reloads the browser window with only that same image. An exception might be where you're linking a small image to a larger one where detail would be visible. Even there, I'd prefer a pop-up window or something that doesn't lose the original context.

To prevent that spurious link, look for this control at the lower right of the insert media pop-up and select Link to: None.

![image](https://cloud.githubusercontent.com/assets/10350595/11460589/d6881402-96a3-11e5-928e-e05a6d393a78.png)

That said, I have updated custom CSS under the theme settings to omit the link icon where the link has a URL ending in jpg, png, or gif. (Instructions I followed are at [1], if interested.) I also omitted the icon on links in unordered lists with class "side-nav." (These are placed by the Pages widget.) 

[1] https://perishablepress.com/css-remove-link-underlines-borders-linked-images/

**Comment by stuartasutton** [comment]
Great, David.

On Sun, Nov 29, 2015 at 2:23 PM, davidwtalley <notifications@github.com>
wrote:

> I have two responses to this. One is to keep WP from doing that automatic
> link-an-image-to-itself that it wants to do by default. That's usually a
> useless link because it reloads the browser window with only that same
> image.
>
Agreed!

**Comment by stuartasutton** [comment]
David, The link icon is still an issue in the page footer where it is located far to the right resulting in it being visually "disconnect" from the associated link.

**Comment by davidwtalley** [comment]
I updated custom CSS in the Avada Theme Options to address this issue, both in the footer and the sliding bar at the top of the page. Please have a look and let me know what you think.

I still want to find a transparent gif of that widely recognized link icon so the white shadow around the arrow will not display.

**Comment by stuartasutton** [comment]
Here are a few transparent versions...including one that is "white" and thus does not show here :-)

![link-gold-icon](https://cloud.githubusercontent.com/assets/2939046/11779846/8693afcc-a212-11e5-8775-dd3f7dbdbd9d.png)
![link-green_light-icon](https://cloud.githubusercontent.com/assets/2939046/11779847/86951c5e-a212-11e5-9ebd-2f5c873711c6.png)
![link-green-icon](https://cloud.githubusercontent.com/assets/2939046/11779848/86968dbe-a212-11e5-92b3-1b7c48deccb3.png)
![link-white-icon](https://cloud.githubusercontent.com/assets/2939046/11779845/86930482-a212-11e5-854c-da3f234ed3e2.png)
